export const GET_COURSE_URL = "GET_COURSE_URL";
export const GET_COURSE_DETAILS = "GET_COURSE_DETAILS";
export const GET_ALL_COURSES = "GET_ALL_COURSES";

export const SEARCH_COURSE = "SEARCH_COURSE";
